### ISSUE TITLE
ENDPOINT option type does not use label

### ISSUE THREAD

**Issue by mattixittam** [bettyblocks/cli#106]
The `ENDPOINT` option type does not use the `label` prop to display its label:

This config:
![Screenshot 2020-03-30 at 11 09 13](https://user-images.githubusercontent.com/2349560/77895433-0e9bfd00-7277-11ea-94c1-933eba21ae0c.png)

Produces this output:
<img width="261" alt="Screenshot 2020-03-30 at 11 09 26" src="https://user-images.githubusercontent.com/2349560/77895435-1065c080-7277-11ea-8ef1-03e2d49e547b.png">

**Comment by larshisken** [comment]
Thanks for taking the time to contribute.

The issue is resolved and will be deployed next release.
