### ISSUE TITLE
Feature request: ability to upgrade components in a page

### ISSUE THREAD

**Issue by mattixittam** [bettyblocks/cli#108]
I would like to be able to upgrade a component in a page when I've made changes to the component in my component set.

Even better: I would like to upgrade it in all my pages (or a subset) at once.

Even betterer: versioning for the component set, and not using the components by cloning but by import/reference. And being able to set the component set version for a page or a subset of pages.

**Comment by larshisken** [comment]
We currently have a experimental feature to update components on your page. You can enable it by adding a custom configuration in Betty Blocks with the name `secret_developer_tools`. Please use with caution.

See https://docs.bettyblocks.com/en/articles/2901778-configurations-reference for more info on configurations.
