### ISSUE TITLE
Make multiple filters available in a prefab

### ISSUE THREAD

**Issue by robinvanderburght** [bettyblocks/cli#128]
The case is: I want to add a default value to the select component. This is based on a 'belongs-to relation' from the datamodel. So the data will be dynamically adjustable in the Backoffice. To achieve this I want to add 2 model options: as source for all options in the select and 1 for the default value. 

Because the default value property also needs filtering I want to add a second filter to the component, but when I want to do this I got this error from the CLI:
`Error: 
Multiple option references to key: filter in prefab: Select`

This case is very common. So is it possible to remove that filter? Or else make the possibility to add it as many times as the model option is present?

**Comment by NiekBetty** [comment]
Hi @robinvanderburght,

You should be able to use 2 filters in one component. The error you get is due to a duplicate option key. Can you try to rename one of the option keys?

E.g.:

```
options: [
  {
    value: {},
    label: 'Filter1',
    key: 'filter',
    type: 'FILTER',
  },
  {
    value: {},
    label: 'Filter 2',
    key: 'filter2',  // <-- Different key then the other FILTER option
    type: 'FILTER',
  },
],
```

Let me know if this fixes your issue and when you have other complications.

**Comment by robinvanderburght** [comment]
This was the cause indeed @NiekBetty 
Thanks for your help! :)
