### ISSUE TITLE
Prefab failed custom validation when trying to add new button component version to existing component set

### ISSUE THREAD

**Issue by saliemamirkhan** [bettyblocks/cli#174]
For a custom component I want to add the latest version of the button component (as seen in the component set repo). When adding the code from this component & prefab to my set and saving it, the compiler gives the following error: 

> Error: 
> Property: "structure[0]" failed custom validation because 
> Build error in prefab Button: "options[7].type" must be one of [ACTION, ACTION_INPUT, AUTHENTICATION_PROFILE, BUTTONGROUP, COLOR, CUSTOM, CUSTOM_MODEL_ATTRIBUTE, DROPDOWN, ENDPOINT, FILTER, FONT, FORM_DATA, MODEL, NUMBER, PROPERTY, PROPERTIES, SIZE, SIZES, TEXT, THEME, TOGGLE, UNIT, VARIABLE]
>  at prefab: Button
> 
> [nodemon] app crashed - waiting for file changes before starting...

When searching about what part of the code this error points to, I find it is in the following: 

        {
          value: [],
          label: 'Property',
          key: 'actionProperties',
          type: 'ACTION_PROPERTIES',
          configuration: {
            apiVersion: 'v1',
            condition: {
              type: 'SHOW',
              option: 'linkType',
              comparator: 'EQ',
              value: 'action',
            },
          },
        },

The error is pointing to the type "ACTION_PROPERTIES" and if I check the release logs of the CLI, this option was added in version 23.15.0. I am running version 23.21.0 so I don't know why this error is still there.

**Comment by dehlak** [comment]
There's also a version of the CLI configured in the package.json of your component set, could it be that this one is outdated?

**Comment by saliemamirkhan** [comment]
I did look at the package.json file and it had "^23.12.0". So I thought it would be okay since it's looking for a version higher than 23.12.0 but I'll try changing it to  "23.21.0" and see what the outcome is.

**Comment by saliemamirkhan** [comment]
Changed the version in de package.json file and the same error occurs. I do have a package-lock,json file where the cli version is 22.39.1, can I just change this version, do I have to delete this file so it can be generated again or does this file have nothing to do with the error?

**Comment by dehlak** [comment]
You can check in the node_modules folder to see which version of the CLI is installed, it's most likely using that one. If that's version 22.39.1 you can safely delete it so that it can be regenerated, to make sure everything is fresh you may also delete the node_modules folder before running `npm install` or `yarn`

**Comment by saliemamirkhan** [comment]
Thank you, it worked. I deleted the whole folder, restarted VS Code and ran "sudo npm install" and the problem was solved.
