### ISSUE TITLE
cli throws error on invalid command

### ISSUE THREAD

**Issue by thomas9911** [bettyblocks/cli#198]
example:

```bash
bb testing
```

response:

```
        throw new Error(chalk_1.default.red(`\nInvalid command: ${command}\n`));
        ^

Error: 
Invalid command: testing
```

expected:

invalid command error with maybe the help text

**Comment by JorisPannekeet** [comment]
Hi @thomas9911 , thanks for this feedback! i've created a task on our backlog to pick this up.
