### ISSUE TITLE
Anker component triggered in builder

### ISSUE THREAD

**Issue by justinvdv** [bettyblocks/cli#22]
When creating an anker component the href will be triggered in the builder itself.

Will also be triggered when :
`{ B.env === 'dev' ? '#' : options.link }` 
`{ options.link || '#' }`
`'javascript:void(0)'`

**Comment by NickRuigrok** [comment]
Try adding this to your anchor tag:

`style={B.env === 'dev' ? {pointerEvents: 'none'} : {}}`

This is working for me 🙂

**Comment by larshisken** [comment]
@justinvdv Does this fix your problem?

**Comment by NiekBetty** [comment]
`href` attributes are now stripped from html elements in the `dev` environment.
