### ISSUE TITLE
B.Text component can't be used as input value

### ISSUE THREAD

**Issue by DylanCarver** [bettyblocks/cli#27]
When retrieving a value with `B.Text`, and using this directly as an input value, I get an input with the value of `[object Object]`, instead of the value from `B.Text`.
```jsx
<input
type="text"
value={<B.Text value={options.variable} />}
 />
```
![Screen Shot 2019-10-11 at 15 48 14](https://user-images.githubusercontent.com/6746411/66656579-9301b180-ec3e-11e9-8415-76d5f6438436.png)

**Comment by larshisken** [comment]
We're going to add a helper function for this.

**Comment by larshisken** [comment]
We added the `useText` hook for this purpose.

Check out the docs at the wiki: https://github.com/bettyblocks/cli/wiki/Component-Helpers#usetext
