### ISSUE TITLE
new version throws error  on multiple component prefabs, example: 'Property 'options' does not exist on type 'PrefabPartial'

### ISSUE THREAD

**Issue by MarzV** [bettyblocks/cli#301]
Version 25.25 throws error when serving te components with: npm run dev.
I updated latest version, when trying tot serve I get this error.log from console:

`npm run dev

> component-set@1.221.0 dev C:\wamp64\www\holygrow\bettyblocks\material-ui-component-set
> nodemon

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: js,ts,tsx
[nodemon] starting `yarn build && yarn start`
yarn run v1.22.17
$ bb components build
Unable to check for a new version
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/autocompleteInput.tsx (12,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/checkboxinput.tsx (26,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/decimalinput.tsx (11,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/emailinput.tsx (11,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/hiddeninput.tsx (19,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/ibaninput.tsx (11,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/numberinput.tsx (11,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/passwordinput.tsx (11,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/phoneinput.tsx (12,60): Property 'options' does not exist on type 'PrefabReference'.onsroperty 'options' does not exist on type 'PrefabPartial'.
  Property 'options' does not exist on type 'PrefabPartial'.                                                         ons' does not exist on type 'PrefabReference'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/phoneinput.tsx (12,60): Property 'options' does not exist on type 'PrefabReference'.                                                                       ons' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/priceinput.tsx (12,60): Property 'optiions' does not exist on type 'PrefabReference'.ons' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.                                                         ptions' does not exist on type 'PrefabReference'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/radioinput.tsx (12,60): Property 'options' does not exist on type 'PrefabReference'.                                                                       ns' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/selectinput.tsx (11,60): Property 'opts' does not exist on type 'PrefabReference'.ions' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/textareainput.tsx (12,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/textinput.tsx (12,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
Error C:/wamp64/www/holygrow/bettyblocks/material-ui-component-set/src/prefabs/urlinput.tsx (13,60): Property 'options' does not exist on type 'PrefabReference'.
  Property 'options' does not exist on type 'PrefabPartial'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.` Please advise how to fix this error ?

**Comment by MarzV** [comment]
Hey Bbérs,
Issue is solved with last pull of the cli. I see that you are not responding to any issues, Why is that ?

**Comment by chrisobdam** [comment]
That's not ok! Let me dive in to that

**Comment by MarzV** [comment]
Hey Chris,
Nice to see you are checking in on issue. Like I said, issues of error is solved. That's said there is still a waring that the check on new CLI versions failed, here is my output when serving the comps.
`[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: js,ts,tsx
[nodemon] starting `yarn build && yarn start`
yarn run v1.22.17
$ bb components build
**Unable to check for a new version**
Success, the component set has been built
Done in 63.34s.
yarn run v1.22.17
$ bb components serve -p 5002
Unable to check for a new version
Serving the component set at http://localhost:5002`

**Comment by chrisobdam** [comment]
Understood, let me get back to that

**Comment by benjamin-rocks** [comment]
Hi @MarzV,

I would like to get some more information on the error you are having. Could you please paste the result of running the following command in your terminal?

```
npm show @betty-blocks/cli version
```

**Comment by MarzV** [comment]
Hey Benjamin-rocks,
give back response of version: 25.27.3

**Comment by benjamin-rocks** [comment]
Hi @MarzV ,

Great you have made progress. However it seems you are now experiencing this issue https://github.com/npm/cli/issues/4234 . It is unfortunately a problem with windows and npm rather than our CLI.

One solution a windows user has found on linked issue is:

> Install nvm 1.1.9 then
> ```
> nvm uninstall 16.15.0
> nvm install 16.15.0
> nvm use 16.15.0
> ```

Let me know if this works for you.

**Comment by MarzV** [comment]
Hey Benjamin, yeah it solved the error
`PS C:\wamp64\www\holygrow\bettyblocks\material-ui-component-set> npm run dev

> component-set@1.225.0 dev
> nodemon

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: js,ts,tsx
[nodemon] starting `yarn build && yarn start`
yarn run v1.22.4
$ bb components build
Checking for new versions..
Done
@betty-blocks/cli update available from 25.27.2 to 25.27.3
Success, the component set has been built
Done in 49.56s.
yarn run v1.22.4
$ bb components serve -p 5002
@betty-blocks/cli update available from 25.27.2 to 25.28.0
Serving the component set at http://localhost:5002`

Tnkz for the help!!!
