### ISSUE TITLE
Missing functions (autoversion and bump) on CLI windows install, getting error Invalid command

### ISSUE THREAD

**Issue by MarzV** [bettyblocks/cli#344]
I have successfully installed the CLI and the described dependecies,

- Bettyblocks/cli25.43.1
- isolated-vm@44.1
- node-gyp9.1.0

But when I try to use the functions

- bb functions autoversion 
- bb funtions bump,

I got an error message **Invalid command.**

When I try BB -h, I see in the list that those functions aren't listed in the list of available functions either.
Can you help me how I get the other functions available on a windows machine ?
![invalid-command](https://user-images.githubusercontent.com/18568753/190111318-6f0ffb49-548a-4f3d-9e55-ab75728c6bc9.png)
![fileStructure](https://user-images.githubusercontent.com/18568753/190112085-8e4aa3c8-f8e2-4e61-ad81-af9b4aafa957.png)

Kind regards,
Marcel van der Vliet
marcel@holygrow.nl
Holygrow

**Comment by MarzV** [comment]
For other with same problems on windows

- when using nvm for windows
- checkout the prefix of the globall installs: npm config get prefix
- add the result of this command to your path variables

That worked for me....

**Comment by chrisobdam** [comment]
Thank you for this update Marcel!
