### ISSUE TITLE
Conditional prefab options

### ISSUE THREAD

**Issue by peterbeers** [bettyblocks/cli#35]
I would like to have the possibility to show/hide prefab options based on another option.

For example I have a Link component and I would like to have the option to:
- select an Endpoint URL 
or
- fill in my own custom URL.

The options appear or disappear based on another option (for example by Radiobutton selection)

**Comment by BarryBlocks** [comment]
Thanks for your feedback! Conditional component options is something that will be picked up in the near future by one of our development teams.

**Comment by NiekBetty** [comment]
@peterbeers conditional options are now available. Documentation can be found here: https://github.com/bettyblocks/cli/wiki/Component-Options#condition

I'll close this issue for now. When you have time can you please check this feature and give us feedbak? Feel free to open this issue again, when you encounter any issues.
