### ISSUE TITLE
Use state in styles

### ISSUE THREAD

**Issue by emielwit** [bettyblocks/cli#36]
I am creating a file upload with live preview. I want to change the background image based on the component state. I want to use my state in styles instead of inline styling.

**Comment by larshisken** [comment]
Currently it's not possible to directly use component state inside the styles. We might add this in the future. For now you can conditionally add classes based on your state, this approach would look something like this:

```jsx
// jsx
const [state, useState] = useState(false);
<div className={state ? classes.foo : classes.bar} />

// styles
{
  foo: {},
  bar: {}
}
```

**Comment by larshisken** [comment]
We recently updated to the newest version of ReactJSS. This allows us to implement the feature you're requesting. Would you still be interested? Of did you find a better solution in the meantime?

**Comment by emielwit** [comment]
Hi, i am still interested? Im now doing it like this:

`let style = {
          filter: 'grayscale(1)',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'cover',
          backgroundImage: `url(${photo})`
        }

<div className={classes.profile} onClick={handleClick} style={style}></div>
`
