### ISSUE TITLE
Loading dependencies

### ISSUE THREAD

**Issue by pwnball** [bettyblocks/cli#37]
I would like to use a library we wrote in our project as a dependency. I take it that we should bundle it ourselves, as it will often change and depending on the Tech team for that would be a burden for both parties. 

1. Can you provide a step by step description on how to use dependencies?

2.. Can you provide the data necessary for bundling our library? Like the expected result, limitations, maybe you have a webpack config we can use as a foundation, etc.

**Comment by larshisken** [comment]
Hey @pwnball,

I added a small write-up in the Wiki on how to add libraries: https://github.com/bettyblocks/cli/wiki/Using-external-JavaScript-libraries-in-your-components

Can you let me know if this is sufficient to get it up and running?
