### ISSUE TITLE
Link to endpoint with query/path variable

### ISSUE THREAD

**Issue by NickRuigrok** [bettyblocks/cli#40]
How to link to an endpoint with a query/path variable so I can use this to retrieve specific data?

**Comment by larshisken** [comment]
Hi @NickRuigrok,

Currently you'll have to do this manually by using the `to` prop on the `Link` component. This accepts a string value (just like React Router).

To make this easier, we could add this to the API of the `Link` component. Do you have any suggestions about how this should work?

**Comment by larshisken** [comment]
Related to #47

**Comment by NiekBetty** [comment]
The `ENDPOINT` option is extended with the ability to provide (dynamic) query params. I will close this issue. Please re-open when problems occur.
