### ISSUE TITLE
<GetAll> with CamelCase models causes a GraphQL error

### ISSUE THREAD

**Issue by JikHuijberts** [bettyblocks/cli#43]
The error occurs when you create a CamelCase model in the backend. Betty converts the datamodel into a snake_case model and will use that in the GraphQL call. GraphQL does not support snake_case modals for now and will generate this error.

This is what the page builder component will give:
`Something went wrong: Network error: Response not successful: Received status code 400 :(`
And this is what the error looks like in the network tab in chrome:
`{"errors":[{"message":"Cannot query field \"random_tables\" on type \"Query\". Did you mean \"randomTables\" or \"randomTable\"?","locations":[{"line":2,"column":3}]}]}`

This could happen with the `<GetOne>` element but I did not test it yet.

**Comment by BarryBlocks** [comment]
Thanks for mentioning! We'll look into this.

**Comment by larshisken** [comment]
This bug has been fixed by a recent release. Is there any way you can test this for us? @JikHuijberts.
