### ISSUE TITLE
Form component doesn't seem to work?

### ISSUE THREAD

**Issue by MarcelKorporaal** [bettyblocks/cli#44]
I've turned CSRF protection off on the post and tried to disable CORS via my.bb but still it doesn't work.
Console error: Access to fetch at 'https://rva-rfp-development.bettywebblocks.com/login' from origin 'https://idenl3.blob.core.windows.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by BarryBlocks** [comment]
Hi @MarcelKorporaal, is this currently still a problem? Please let me know, then we'll look into it!
