### ISSUE TITLE
Feature: It would be nice to allow all types of components inside a component

### ISSUE THREAD

**Issue by roy-willemse** [bettyblocks/cli#45]
To improve reusability of our components it would be very beneficial to allow all types inside a component. 

Perhaps something like this:
`allowedTypes: [
    '*'
  ]` 

Instead of:
`allowedTypes: [
    'ACCORDION',
    'ALERT',
    'BREADCRUMB',
    'BUTTON',
    'DATALIST',
    'DATATABLE',
    'DIVIDER',
    'FORM',
    'IMAGE',
    'PARTIAL',
    'PANEL',
    'PROGRESS',
    'TABS',
    'TEXT',
    'TODO_ITEMS',
    'DEPENDENCIES',
  ],`

This is especially handy for container components and would save a lot of time in our projects.

**Comment by BarryBlocks** [comment]
Thanks for your feedback! I've added this request to the backlog.

**Comment by larshisken** [comment]
@roy-willemse 

Would this also allow you to drop a component of the same type? E.g. `ROW`->`ROW`. What do you expect in this scenario?

**Comment by roy-willemse** [comment]
@larshisken I discussed this with some colleagues and we think it should be possible to drop a component of the same type on the same time like your example. so `ROW` => `ROW` should be possible.

**Comment by larshisken** [comment]
@roy-willemse 

Thanks for the quick reply. I'll discuss this internally and see if we can add it in the near future.
