### ISSUE TITLE
Global state across multiple pages

### ISSUE THREAD

**Issue by roy-willemse** [bettyblocks/cli#46]
I would like to use global state management for our projects. I thought that useContext would be the solution however it looks like this context object reinitialises after rendering a different page with the link component `<Link  endpointId="3cc962c6d1ce46519fa428822f28480d">home</Link>`

Right now I want to use this in my custom authentication component which will probably soon be obsolete but I think that we can use this for all dynamic global states.

**Comment by chrisobdam** [comment]
Ey Roy, what's your use case? What do you want to achieve functionally?

**Comment by roy-willemse** [comment]
Hey Chris, thanks for your response.
I will try to elaborate on my use case.

![Screenshot 2019-10-28 at 11 04 59](https://user-images.githubusercontent.com/3258772/67669814-ed0ab280-f972-11e9-87dd-cb91b6e2703e.png)

As you can see in the screenshot above, I have created a navigation bar with the name of the logged in user. This navigation bar is placed on pages that need authentication. 

In the future you can hopefully just select the global variable in an option but for now I'm doing a `fetch()` to retrieve this information. 

If we have global state management you could save the name of the logged in user so this information doesn't need to be re-fetched on every page.

I think we could also use this for things like multi step checkouts in the case that you only want to save data when the user submits the last page.

There are workarounds for this, right now I'm using sessionStorage but this is not the cleanest way. I would prefer to use useContext for this.

I think if the useContext didn't reset after linking to a different page we would have more flexibility.

Summary:
As a developer I would like useContext to keep the state even when linking to different pages using the `<link>` component or the `useHistory` hook to gain more flexibility in solving multiple pages flows.

**Comment by larshisken** [comment]
As a workaround you could store global state in the query params (e.g. /person?state=foobar). If this doesn't fit your application design, you can always use sessionStorage (https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)

**Comment by mattixittam** [comment]
Does this mean that global state will not be supported or is it on the roadmap?
