### ISSUE TITLE
Link tag with an endpointId and query parameters

### ISSUE THREAD

**Issue by louise-vandenberg** [bettyblocks/cli#47]
Please have a look at the process of sending query parameters when you only have an endpointId via the <Link> tag

**Comment by BarryBlocks** [comment]
Thanks for your feedback! We'll take this into account.

**Comment by NiekBetty** [comment]
The `ENDPOINT` options is extended with the ability to provide (dynamic) query params. I will close this issue. Please re-open when problems occur.
