### ISSUE TITLE
How to set the Page title and Set a Favicon?

### ISSUE THREAD

**Issue by Master244** [bettyblocks/cli#54]
`<head>
    <title>Betty Blocks</title>
    <meta charset="utf-8">
    <meta name="description" content="Made with Betty Blocks">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

These values can't be set in the new page builder yet.

**Comment by ThomasVlaar** [comment]
Hi @Master244,  thanks for reaching out! This is not possible yet. We are investigating the priority of this feature. It is in our backlog.

**Comment by Master244** [comment]
For SEO purposes this is a must. :)

**Comment by BarryKraakman** [comment]
Thanks for your input; we're aware of this feature request. However, this issue isn't related to the CLI, thus it will be closed.
