### ISSUE TITLE
Options in styling generate multiple classes

### ISSUE THREAD

**Issue by justinvdv** [bettyblocks/cli#56]
When using options in styling the class will be rendered twice on the component.
for example:

```
return {
      root: {
        width: ({ options: { width } }) => width,
      },
}
```

will generate a html element like this:

```
<div class="root-0-2-9 root-0-0-2-15"></div>
```

When I hardcode width to a static width the root class is shown once.

**Comment by larshisken** [comment]
Is this causing any issues?

**Comment by justinvdv** [comment]
Sometimes it does. Not with the root class but with own generated classes. For example

`<div className={[classes.root, classes[options.horizontalPosition], classes[options.verticalPosition]].join(' ')}>`

 classes[options.horizontalPosition], classes[options.verticalPosition] will now be generated 4 times. This can trigger some weird side effects on styling.

**Comment by NiekBetty** [comment]
Hi Justin,

What kind of side effects? We would like to reproduce your problem before thinking of a solution.
