### ISSUE TITLE
Root inserted on every page

### ISSUE THREAD

**Issue by AnitaHeiblom** [bettyblocks/cli#59]
A div element with class root is inserted on every page below the "<div id="app"> element. This element adds styling to the page and overwrites our own global styling (for example font-family). 
Is there any way we can change or remove this element?

**Comment by larshisken** [comment]
Hi @AnitaHeiblom,

Currently the Page Builder itself uses the root component for drag&drop behavior, I think removing it would not be possible in the near future. Would allowing you to change the styling (e.g. `font-family`) of the root be sufficient to solve your use case?

**Comment by AnitaHeiblom** [comment]
Yes!
