### ISSUE TITLE
/Login

### ISSUE THREAD

**Issue by justinvdv** [bettyblocks/cli#62]
/login page is preserved?

This is how '/login' looks like in the pagebuilder
![Schermafbeelding 2019-12-03 om 16 50 39](https://user-images.githubusercontent.com/22611783/70066528-2aef9c00-15ed-11ea-95b2-928b7ff66c97.png)

But it's rendering a different page in runtime
![Schermafbeelding 2019-12-03 om 16 50 48](https://user-images.githubusercontent.com/22611783/70066553-317e1380-15ed-11ea-9e4e-8779986f6818.png)

**Comment by BarryKraakman** [comment]
@justinvdv This is expected behaviour. As workaround, you can use any other url (e.g. /log-in). But please know that this isn't a CLI-issue, and shouldn't be issued here.
