### ISSUE TITLE
Publishing with env variables generates errors

### ISSUE THREAD

**Issue by MarzV** [bettyblocks/cli#64]
Excerpt From the readme

The publish command requires you to set the following environment variables:
AZURE_BLOB_ACCOUNT
AZURE_BLOB_ACCOUNT_KEY

I have tried to setup the env file with these variables, but on publishing BB generates an
error that variables are not defined.

Please Explain in detail how to setup env variables in the bettyblocks package.json

For other users with same errors, see below an alternative setup. With this you can check out your component with all the avalilable options , that is if you are using the fantastic BettyBlocks platform.

![image](https://user-images.githubusercontent.com/18568753/70441868-77c3ee80-1a95-11ea-97cb-972781a11115.png)

**Comment by MarzV** [comment]
Hey BB's,

I am trying to preview my hello-world component in the new UI builder. But is does not work.
Is there a change in the setup of the UI builder how to preview my custom-components, please explain?

- I am running the dev server at hhtp://localhost:5001
- This is my pagebuilder setting screen

![image](https://user-images.githubusercontent.com/18568753/78595954-3842be80-784b-11ea-8103-c34c29dead9a.png)

I am missing the options BETTYBLOCKS COMPONENTEN, toon en verberg.

**Comment by chrisobdam** [comment]
Hi, your custom components will be shown on the components palette. The first tab of this view, what do you see on that tab?

**Comment by MarzV** [comment]
Hey Chris,

the components palette does NOT show my 'Hello world' component. Here are some data about my configuration:

**Server is running:**
![image](https://user-images.githubusercontent.com/18568753/78695509-7fd65280-78fe-11ea-9f67-4dfcd5860ff4.png)

**Preview is running:**
![image](https://user-images.githubusercontent.com/18568753/78695835-ed827e80-78fe-11ea-90a3-3336a9e22290.png)

**The output on http://localhost:5001/**
![image](https://user-images.githubusercontent.com/18568753/78696233-73062e80-78ff-11ea-95b1-e5f3bade5026.png)

**content of prefabs.json:**
[{"name":"Hello world","icon":"TitleIcon","category":"CONTENT","structure":[{"name":"HelloWorld","options":[{"value":"","label":"Content","key":"content","type":"TEXT"},{"value":"title2","label":"Heading type","key":"headingType","type":"CUSTOM","configuration":{"as":"BUTTONGROUP","dataType":"string","allowedInput":[{"name":"1","value":"title1"},{"name":"2","value":"title2"},{"name":"3","value":"title3"},{"name":"4","value":"title4"}]}}],"descendants":[]}]}]

**content of templates.json:**
[{"name":"HelloWorld","type":"ROW","allowedTypes":[],"orientation":"HORIZONTAL","jsx":"<h1 className={classes.root}>{options.content || 'Hello world Mars'}</h1>","styles":"B => ({\n  typography\n}) => ({\n  root: {\n    fontFamily: ({\n      options: {\n        headingType\n      }\n    }) => typography[headingType].family,\n    fontSize: ({\n      options: {\n        headingType\n      }\n    }) => typography[headingType].mobileSize,\n    fontWeight: ({\n      options: {\n        headingType\n      }\n    }) => typography[headingType].weight,\n    textTransform: ({\n      options: {\n        headingType\n      }\n    }) => typography[headingType].textTransform,\n    textAlign: ({\n      options: {\n        textAlignment\n      }\n    }) => textAlignment,\n    letterSpacing: ({\n      options: {\n        headingType\n      }\n    }) => typography[headingType].letterSpacing,\n    color: ({\n      options: {\n        headingType,\n        color\n      }\n    }) => color || typography[headingType].color,\n    [`@media ${B.mediaMinWidth(768)}`]: {\n      fontSize: ({\n        options: {\n          headingType\n        }\n      }) => typography[headingType].tabletPortraitSize\n    },\n    [`@media ${B.mediaMinWidth(1024)}`]: {\n      fontSize: ({\n        options: {\n          headingType\n        }\n      }) => typography[headingType].tabletLandscapeSize\n    },\n    [`@media ${B.mediaMinWidth(1200)}`]: {\n      fontSize: ({\n        options: {\n          headingType\n        }\n      }) => typography[headingType].desktopSize\n    }\n  }\n})"}]

**Sceen of pallete tab:**
![image](https://user-images.githubusercontent.com/18568753/78696518-d728f280-78ff-11ea-83e3-c3b16d38319a.png)

I am able to invite a BB developers to the app if needed. Hope this info will help to solve my problem.

**Comment by chrisobdam** [comment]
Is your goal to use it in the IDE, or in the previewer?

**Comment by MarzV** [comment]
Hey Chris, main goal is in the IDE, that is where the magic happens;-)

**Comment by chielwester** [comment]
Hi, in the settings tab, the component set url is a placeholder, did you actually set it to http://localhost:5001 ? Seems like you're still having our default component set

**Comment by MarzV** [comment]
Hey Chiel, that fixed the problem. Perhaps a for example addition to the placeholder will be nice?.
Tnkz for your help!. Will close Issue!
