### ISSUE TITLE
Pass data to all child components

### ISSUE THREAD

**Issue by robinvanderburght** [bettyblocks/cli#67]
Now it's only possible with B.Children to pass data to only direct child components. It would be great if this is passed to all child components and accessible with const {value} = parent; 

So for example I have a parent component that fetches some data.
The parent component has a row with a column als child components. Inside the column component there's a component that's showing the data from the top parent component.

**Comment by larshisken** [comment]
The concept you are proposing is called "prop drilling". I think there are other (better) ways to solve this. E.g. by using a React Context. https://reactjs.org/docs/context.html
