### ISSUE TITLE
2-column component row breaks when it is last component on canvas

### ISSUE THREAD

**Issue by BasBetty** [bettyblocks/cli#8]
<img width="1133" alt="Schermafbeelding 2019-10-03 om 14 23 30" src="https://user-images.githubusercontent.com/55531051/66126329-84d1e680-e5e9-11e9-9282-d96128247775.png">

**Comment by BasBetty** [comment]
<img width="1125" alt="Schermafbeelding 2019-10-03 om 14 25 07" src="https://user-images.githubusercontent.com/55531051/66126386-9f0bc480-e5e9-11e9-9883-b7bb8df212ed.png">

**Comment by larshisken** [comment]
Can you give me a bit more information about the actual components that are being used?
