### ISSUE TITLE
Failed to fetch :(

### ISSUE THREAD

**Issue by gijsvanwichen** [bettyblocks/cli#84]
I would like fetch project data:
<img width="1278" alt="Schermafbeelding 2019-12-24 om 15 50 24" src="https://user-images.githubusercontent.com/59204270/71417423-84d00880-2665-11ea-92b9-05b4aa81dac8.png">

When you build the page, you see this screen:
<img width="1277" alt="Schermafbeelding 2019-12-24 om 15 50 52" src="https://user-images.githubusercontent.com/59204270/71417447-a4ffc780-2665-11ea-997b-4e40e80feb9f.png">

And then the graphql server goes down:
<img width="1277" alt="Schermafbeelding 2019-12-24 om 15 51 01" src="https://user-images.githubusercontent.com/59204270/71417491-d2e50c00-2665-11ea-8b40-a27fb1fdf6f6.png">

**Comment by BarryBlocks** [comment]
Thanks for reporting, we'll look into it!

**Comment by BarryBlocks** [comment]
Hi Gijs, please only report CLI-related issues in this repo!

**Comment by larshisken** [comment]
Hi, @gijsvanwichen, this will be fixed in one of the upcoming releases. For now you could work around this issue by using a custom Betty Blocks endpoint to fetch the data.
